jodconverter_url: "http://localhost:8080/converter/service"
lexkimbookreports_home: "http://lexkimbookreports.com"
lexkimbookreports_home_ssl: "https://lexkimbookreports.com"
data_dir: "/var/data/lexkimbookreports"
admin_emails: ['lex_admin@barrelny.com']
